- menu_name: "Subscribe by"

- name: "Twitter"
  url: "https://twitter.com/OnDataEng"
  title: "Follow us on twitter"

- name: "E-Mail"
  url: "http://eepurl.com/cyQSqv"
  title: "Subscribe to updates by e-mail"

- name: "Atom"
  url: "/atom.xml"
  title: "Subscribe to Atom Feed"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"